/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-primary-fixed": "#00201b",
          "secondary-container": "#48494c",
          "primary-container": "#2febd2",
          "error-container": "#93000a",
          "surface-container-high": "#232b31",
          "on-secondary-fixed-variant": "#46474a",
          "inverse-primary": "#006b5e",
          "on-background": "#dbe3ec",
          "surface": "#0c141a",
          "outline-variant": "#3b4a46",
          "on-error": "#690005",
          "surface-bright": "#323a41",
          "on-secondary-fixed": "#1a1b1e",
          "on-primary-fixed-variant": "#005047",
          "tertiary-container": "#d2d2d9",
          "surface-variant": "#2e363c",
          "background": "#0c141a",
          "on-tertiary-container": "#585a60",
          "secondary": "#c7c6ca",
          "on-tertiary": "#2e3035",
          "on-primary-container": "#00665a",
          "surface-container-highest": "#2e363c",
          "on-primary": "#003730",
          "on-tertiary-fixed-variant": "#45474c",
          "primary-fixed": "#4bfce2",
          "surface-dim": "#0c141a",
          "surface-container": "#192127",
          "surface-container-low": "#151c22",
          "tertiary-fixed-dim": "#c5c6cc",
          "on-error-container": "#ffdad6",
          "on-secondary": "#2f3033",
          "secondary-fixed": "#e3e2e6",
          "outline": "#849490",
          "secondary-fixed-dim": "#c7c6ca",
          "on-secondary-container": "#b9b8bc",
          "primary": "#a8ffee",
          "on-surface-variant": "#bacac5",
          "surface-tint": "#08dfc6",
          "primary-fixed-dim": "#08dfc6",
          "on-tertiary-fixed": "#191c20",
          "error": "#ffb4ab",
          "inverse-surface": "#dbe3ec",
          "inverse-on-surface": "#293138",
          "tertiary-fixed": "#e2e2e8",
          "surface-container-lowest": "#070f15",
          "tertiary": "#eeeef5",
          "on-surface": "#dbe3ec"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "maxWidth": {
          "xs": "20rem",
          "sm": "24rem",
          "md": "28rem",
          "lg": "32rem",
          "xl": "36rem",
          "2xl": "42rem",
          "3xl": "48rem",
          "4xl": "56rem",
          "5xl": "64rem",
          "6xl": "72rem",
          "7xl": "80rem",
      },
      "spacing": {
          "base": "4px",
          "margin-desktop": "40px",
          "xs": "8px",
          "xl": "48px",
          "sm": "16px",
          "gutter": "20px",
          "md": "24px",
          "lg": "32px",
          "margin-mobile": "16px"
      },
      "fontFamily": {
          "headline-lg": ["Hanken Grotesk"],
          "label-caps": ["JetBrains Mono"],
          "code-sm": ["JetBrains Mono"],
          "headline-md": ["Hanken Grotesk"],
          "headline-lg-mobile": ["Hanken Grotesk"],
          "body-md": ["Inter"],
          "body-lg": ["Inter"]
      },
      "fontSize": {
          "headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "code-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "headline-lg-mobile": ["30px", {"lineHeight": "36px", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
