import type { Educational } from "../schemas/findings.js";

const GENERIC: Educational = {
  what: "El analizador encontró un patrón asociado típicamente con riesgos de seguridad cuando se comparte el código tal cual sin revisión humana.",
  why: "La IA y plantillas rápidas suelen copiar credenciales ficticias o prácticas peligrosas “que funcionan en local” pero jamás deberían publicarse.",
  impact: "Los atacantes podrían automatizar búsquedas de estos patrones y obtener acceso temporal a cuentas de pago, infraestructura o datos personales.",
  whoAffected: "Usuarios finales, tus clientes empresariales, el equipo de soporte y tus propias llaves de desarrollador podrían sufrir abuso de recursos o robo de reputación.",
};

export const EDU_TEMPLATES: Record<string, Educational> = {
  SECRET_SENSITIVE_FILENAME: {
    what: "Hay un archivo cuyo nombre sugiere guardar credenciales fuera de un lugar seguro especializado.",
    why: "Las credenciales en carpetas compartidas pueden subirse accidentalmente a chats, repositorios o copias de seguridad no cifradas.",
    impact: "Cualquiera con acceso al proyecto (o con un enlace público) puede reutilizar tus claves antes de que puedas desactivarlas.",
    whoAffected: "Tú, tu equipo DevOps, clientes del servicio y personas cuyos datos se hospedan tras esas llaves.",
  },
  SECRET_AWS_KEY: {
    what: "Hay un texto muy parecido a una llave de AWS (ID de acceso). Confirma manualmente si son datos reales antes de desestimarlo.",
    why: "Crackers buscan exactamente este patrón porque controla recursos en la nube con facturación inmediata.",
    impact: "Se puede encender minería, borrar datos críticos o exfiltrarlos en menos de minutos si la clave es válida.",
    whoAffected: "Finanzas de la empresa y todos los sistemas alojados detrás de esa cuenta en la nube.",
  },
  SECRET_OPENAI_SK: {
    what: "Parece un token de API muy potente dentro del código textual.",
    why: "Quienes lo encuentren pueden consumir tu saldo técnico, entrenamientos o cargar tus cuotas sin permiso.",
    impact: "Gastos sorpresa, pérdida de privacidad de prompts corporativos o bloqueos de proveedor.",
    whoAffected: "El propietario de la cuenta de facturación y los proyectos donde se reusaba ese token.",
  },
  SECRET_GENERIC_API: {
    what: "Un token de desarrollador (GitHub/GitLab u otro) podría haberse copiado al pegar ejemplo de código.",
    why: "Plataforma de desarrollo es blanco habitual: combinación de reputación alta + automatización mal protegida.",
    impact:
      "Incluso permisos de lectura reducidos pueden filtrarnos secreto siguiente (cadena lateral) o ejecutar código en pipelines.",
    whoAffected:
      "Repositorios afectados, issues privados listados y automatizaciones configuradas dentro de ese servicio.",
  },
  SECRET_RSA_BLOCK: {
    what: "Un bloque PEM de clave privada fue detectado dentro de archivos de texto revisados.",
    why: "Esa pieza permite descifrar conexiones o firmar payloads como si fueras tú con privilegio total.",
    impact: "Alguien podría suplantarte en VPN, TLS intermedios o infraestructura interna antes de cerrar Incident Response.",
    whoAffected:
      "Cualquier sistema que dependa de esa infraestructura criptográfica (VPN, bastiones SSH, gateways).",
  },
  DEPS_SUPPLY_CHAIN: {
    what: "Una librería con nombre cercano al popular aparece declarada junto tu aplicación principal.",
    why: "Atacantes publicaron paquetes “casi idénticos” para engañar a build scripts y CI sin supervisión.",
    impact: "El build podría ejecutar scripts maliciosos silenciosos que roban variables de entorno durante `npm install`.",
    whoAffected: "Ingenieros que importan la dependencia y cada entorno productivo que la empaqueta.",
  },
  PATTERN_EVAL_JS: {
    what: "El código intenta ejecutar texto dinámico como si fuera instrucción real del lenguaje.",
    why: "Si una sola cadena proviene de usuario o de un JSON remoto, el atacante puede correr sus propias instrucciones.",
    impact: "Control remoto del servidor o del navegador según el contexto, robo de cookies, lectura de disco o APIs internas.",
    whoAffected: "Visitantes de la web, clientes finales y la reputación de tu dominio en listas de malware.",
  },
  PATTERN_NEW_FUNCTION: {
    what: "Se construyen funciones en tiempo de ejecución a partir de texto plano.",
    why: "Es un atajo que la IA sugiere para “flexibilidad”, pero abre el mismo vector que `eval` en muchos casos.",
    impact: "Ejecución remota de código si el material de entrada no está 100% curado y versionado.",
    whoAffected: "La misma superficie que `eval`: usuarios autenticados y operadores de la app.",
  },
  PATTERN_CHILD_PROCESS_SHELL: {
    what: "El backend prepara órdenes del sistema operativo concatenando textos.",
    why: "Un carácter mal colocado en la entrada del usuario transforma el comando benigno en borrado o exfiltración.",
    impact: "Compromiso del host, pérdida de backups montados como volúmenes o escalada lateral dentro de VPC.",
    whoAffected:
      "Equipo de infraestructura completo porque el shell corriendo seguramente tiene acceso LAN ampliamente abierto legacy.",
  },
  PATTERN_HTML_INJECTION: {
    what: "Se escribe HTML “crudo” en el navegador a partir de variables dinámicas.",
    why: "Navegador confía tu app: si XSS entra desde input, ejecuta Javascript “como usuario logueado”.",
    impact: "Robo de sesión admins, phishing embebido, redireccion malicioso a descargador de ransomware.",
    whoAffected:
      "Cualquier cuenta logueada mientras navega ese componente específico, incluído equipo interno usando admin panel.",
  },
  PATTERN_SQL_CONCAT_POSSIBLE: {
    what: "Se encontró SQL seguido de una plantilla con datos típicamente tomados desde la petición (req/body/etc.).",
    why: "Eso suele aparecer antes de parametrizaciones correctas. Un apóstrofe mal escapado abre vectores conocidos desde hace años.",
    impact: "Fuga GDPR masiva o manipulaciones financieras al descubrir comandos DDL/DML adicionales con la cuenta del servicio.",
    whoAffected:
      "Titulares de datos, auditores, legal y equipo operaciones que enfrentará incident-response multi-día recuperando backups válidos.",
  },
  PATTERN_SQL_PRISMA_RAW_UNSAFE: {
    what: "Se encontró método Prisma explícito para SQL crudo poco supervisado.",
    why: "Generar SQL sin plantillas parametrizadas hace muy fácil que la IA sugiera interpolación textual sin validar tamaño/formato.",
    impact: "Riesgo de lectura/modificación destructiva usando credenciales válidas pero engañadas mediante payload SQL multi-línea.",
    whoAffected: "Todos los registros hospedados bajo ese connection string hasta que se fuerce failover y auditoría diferencial.",
  },
  PATTERN_PYTHON_PICKLE: {
    what: "`pickle` vuelve a construir objetos Python arbitrarios desde bytes externos.",
    why: "Ese proceso puede lanzar código arbitrario durante deserialización sin pop-up de confirmación visible.",
    impact: "Shell remoto en worker de batch o cola de mensajes que procesa jobs subidos por usuario final.",
    whoAffected: "Operaciones que confían en jobs serializados (ETL, ML pipelines, colas admin).",
  },
  PATTERN_PYTHON_YAML_UNSAFE: {
    what: "Se llama `yaml.load` clásico en vez de `safe_load`.",
    why: "YAML puede incrustar tipos que disparan constructores peligrosos si el stream no es 100% confiable.",
    impact: "RCE en servicio de configuración que lee archivos subidos por partner integración externa.",
    whoAffected: "Partners B2B que comparten plantillas `.yml` y cualquier microservicio downstream que confíe ciegamente.",
  },
  PATTERN_COOKIE_HTTPONLY: {
    what: "Se configura una cookie de sesión accesible por Javascript en el cliente.",
    why: "Si otro bug XSS aparece, el script malicioso puede copiar la cookie y reutilizarla fuera del navegador víctima.",
    impact: "Session riding prolongado aunque la víctima cierre tab (depende longitud expiración).",
    whoAffected: "Cuentas de usuarios de la app y administradores con panel expuesto al mismo bundle JS.",
  },
  CONFIG_DOTENV: {
    what: "Archivo `.env` con secretos reales forma parte del material analizado.",
    why: "Es el vector #1 de filtración accidental en vibe coding: “funciona en local” → commit por error.",
    impact: "Acceso pleno a DB productiva, APIs de pago, buckets S3 con dumps personales descargables.",
    whoAffected: "Personal de datos, legal y clientes cuyo PII quedó desprotegido tras robo de credencial DB.",
  },
  CONFIG_CORS_STAR: {
    what: "Se indica `Access-Control-Allow-Origin: *` o equivalente demasiado amplio en backend.",
    why: "Navegador confía la política: dominio malicioso puede disparar peticiones autenticadas si credenciales enabled.",
    impact: "Robo de JSON privado vía browser del usuario engañado con click en link malicioso embutido.",
    whoAffected: "Usuarios logueados y cuentas con cookies de sesión larga (admin + customer).",
  },
  CONFIG_DEBUG_ENABLED: {
    what: "Hay banderas de depuración explícitas en código accesible al build final.",
    why: "Debug verboso expone variables internas y paths de archivos en disk productivo.",
    impact: "Facilita cadena de ataques (path traversal, enumeración servicios escondidos).",
    whoAffected: "Equipo de seguridad que debe triagear incidente y marketing si filtra roadmap interno en error page.",
  },
  CONFIG_PUBLIC_SECRET_NAME: {
    what: "Variables que el navegador puede leer incluyen palabras reservadas de secreto en su nombre mismo.",
    why: "Indica alta probabilidad que se planea exponer secreto verdadero al público sólo porque “NEXT_PUBLIC debe existir”.",
    impact:
      "Cualquier visitante scrapea tus API keys igual que tus archivos `.js` minificados (no hay manera de ocultarlo).",
    whoAffected:
      "Cualquier integración SaaS donde la key permite facturarte o crear recursos externos con tu nombre marca.",
  },  // A02 Extended Secrets
  SECRET_DB_CONNECTION_STRING: {
    what: "Una cadena de conexión a base de datos con credenciales embebidas fue detectada.",
    why: "Contiene usuario, contraseña y host del servidor. Si se expone, cualquiera puede iniciar sesión como ese usuario.",
    impact: "Acceso pleno a toda la BD, posibilidad de borrar tablas, exportar datos o manipular registros.",
    whoAffected: "Todos los clientes cuyos datos PII/financiero se hospedan en esa base de datos.",
  },
  SECRET_AWS_SECRET_ACCESS_KEY: {
    what: "Detectada clave secreta de acceso (AWS Secret Access Key) en el código.",
    why: "Junto con el Access Key ID, permite toda operación en la cuenta AWS asociada sin restricción.",
    impact: "Encendido de instancias costosas, creación de DBs para minería, borrado de backups, robo de EBS snapshots.",
    whoAffected: "Finanzas de la empresa (factura sorpresa inmediata) y equipo DevOps que pierde control de infraestructura.",
  },
  SECRET_AWS_ACCOUNT_ID: {
    what: "Un ARN de AWS incluyendo el ID de cuenta fue encontrado en archivos.",
    why: "Aunque es información parcialmente descubrible, confirma tu estructura y facilita fuzzing de recursos.",
    impact: "Información enumeration attack: descubrir buckets S3, instancias, volúmenes asociados a esa cuenta.",
    whoAffected: "Equipo de seguridad en respuesta a ataque; atacante conoce tu infraestructura de AWS.",
  },
  SECRET_STRIPE_API_KEY: {
    what: "Clave de API de Stripe (sk_live o sk_test) fue hallada.",
    why: "Permite procesamiento y modificación de pagos directamente en tu cuenta Stripe.",
    impact: "Robo de fondos, creación de cargos falsos, refunds no autorizados, acceso a clientes y datos de tarjeta.",
    whoAffected: "Clientes cuyos datos de tarjeta se procesan; finanzas por fraude y reputación de negocio.",
  },
  SECRET_STRIPE_PUBLISHABLE_KEY: {
    what: "Clave publicable de Stripe está en código (bajo scrutinio porque es 'pública').",
    why: "Aunque Stripe keys públicas son por diseño públicas, revisar contexto: ¿en .env privado? ¿test vs live?",
    impact: "Bajo (pública por diseño), pero si es sk_live puede permitir fraude. Si es test, no harm.",
    whoAffected: "Bajo. Revisión manual recomendada para confirmar que es test o no le importa exposición.",
  },
  SECRET_TWILIO_API_KEY: {
    what: "Credenciales de Twilio (Account SID + Auth Token) fueron detectadas.",
    why: "Permite envío de SMS, llamadas, y modificación de configuración en tu cuenta Twilio.",
    impact: "Spam SMS/voice a listas de clientes, modificación de números, interceptación de 2FA tokens.",
    whoAffected: "Clientes de app (spam y phishing 2FA), marca reputation por abuse de canal SMS.",
  },
  SECRET_SENDGRID_API_KEY: {
    what: "API key de SendGrid está presente en código.",
    why: "Permite envío de emails desde tu cuenta, modificación de templates y listas de contacto.",
    impact: "Spam/phishing masivo a tus contactos, robo de datos de suscripción, daño a reputación de dominio.",
    whoAffected: "Listas de contactos/clientes; dominios rastreados por SendGrid pueden darse de baja ESPs.",
  },
  SECRET_FIREBASE_DATABASE_URL: {
    what: "URL de Firebase Realtime Database o Firestore fue encontrada.",
    why: "Aunque es nombre del proyecto (semi-público), confirma dónde están tus datos.",
    impact: "Facilitación enumeration; combinada con Firebase security rules débiles permite lectura/escritura no autorizada.",
    whoAffected: "Bajo si reglas restrictivas. Alto si reglas default: 'allow read, write'.",
  },
  SECRET_FIREBASE_CONFIG: {
    what: "Configuración de Firebase (apiKey, projectId) está en código.",
    why: "Estos valores son semi-públicos pero confirman estructura. apiKey no es secreto, projectId sí revela mucho.",
    impact: "Bajo si Firestore rules son estrictas. Alto si default open rules.",
    whoAffected: "Depende Firebase security rules configuration.",
  },
  SECRET_GCP_API_KEY: {
    what: "API key de Google Cloud Platform fue detectada.",
    why: "Permite acceso a servicios GCP bajo esa clave hasta que se revoque.",
    impact: "Acceso a Cloud Storage, BigQuery, Cloud Run, ML APIs bajo cuota de la clave.",
    whoAffected: "Finanzas (billing), equipo de datos (BigQuery access), infraestructura (Cloud Run).",
  },
  SECRET_GCP_SERVICE_ACCOUNT: {
    what: "Archivo JSON service account de GCP con private key está presente.",
    why: "Service account auth completa a GCP sin segundo factor.",
    impact: "Acceso pleno a todos servicios GCP asignados a esa service account (máximo daño).",
    whoAffected: "Equipo ops, finanzas, acceso a todos recursos vincluados: buckets, datasets, clusters Kubernetes.",
  },
  SECRET_GITHUB_OAUTH_TOKEN: {
    what: "Token OAuth personal de GitHub fue hallado.",
    why: "Permite operaciones en repos, ejecución de workflows, creación de deploy keys.",
    impact: "Acceso a repositorios privados, inyección de código en CI/CD, exfiltración de secretos en Actions.",
    whoAffected: "Repositorios del usuario; si incluyen keys production, acceso a prod infrastructure.",
  },
  SECRET_GITLAB_TOKEN: {
    what: "Token de GitLab (personal o CI/CD) fue detectado.",
    why: "Permite push de código, acceso a pipelines, modificación de protecciones de branch.",
    impact: "Bypass de code review, ejecución maliciosa en CI/CD pipeline, acceso a deploy secrets.",
    whoAffected: "Repositorios; si CI/CD token, acceso a entornos productivos y secretos desplegables.",
  },
  SECRET_JWT_HARDCODED: {
    what: "Un JWT (token.payload.signature) parece estar hardcodeado.",
    why: "Si es un JWT válido hardcodeado, indica token estático reutilizable.",
    impact: "Session riding prolongado si token no expira o expiración muy distante.",
    whoAffected: "Cuentas cuyo JWT fue embebido en código (generalmente admin/test).",
  },
  SECRET_AZURE_CONNECTION_STRING: {
    what: "Connection string de Azure (Storage/SQL) con AccountKey fue encontrada.",
    why: "Contiene claves primarias de acceso a recursos Azure.",
    impact: "Acceso pleno a Azure Storage blobs/tables, SQL Database, recursos cloud.",
    whoAffected: "Datos en Azure Storage/SQL; finanzas si se gasta en compute resources.",
  },
  SECRET_AZURE_CLIENT_SECRET: {
    what: "Client Secret de Azure AD/Entra fue detectado.",
    why: "Permite autenticación de aplicación contra Azure AD/Entra sin MFA.",
    impact: "Acceso a Azure resources, Microsoft Graph, integración O365.",
    whoAffected: "Acceso directory/O365 del tenant Azure AD; posible lateral movement en infraestructura.",
  },
  SECRET_RSA_PUBLIC_KEY: {
    what: "Clave pública RSA está presente (por definición es pública).",
    why: "No es secret, pero revisar contexto: ¿se expone accidentalmente del disco?",
    impact: "Bajo (pública). Verifica que sea realmente key pública y no private en nombre incorrecto.",
    whoAffected: "Bajo bajo",
  },
  SECRET_SSH_PRIVATE_KEY: {
    what: "Clave privada SSH está en el repositorio.",
    why: "Permite iniciar sesión en servidores remotos sin contraseña como ese usuario.",
    impact: "Acceso remoto a todos servidores donde esa clave está en authorized_keys.",
    whoAffected: "Cualquier servidor con esa clave autenticada; posible pivote a otros hosts.",
  },
  SECRET_GENERIC_BEARER_TOKEN: {
    what: "Authorization header con token Bearer está hardcodeado.",
    why: "Indica credencial reutilizable embebida en aplicación.",
    impact: "Acceso al endpoint/servicio usando esa credencial de forma permanente.",
    whoAffected: "Endpoint protegido; usuario cuyo token fue capturado.",
  },
  SECRET_DJANGO_SECRET_KEY: {
    what: "Django SECRET_KEY fue encontrada en código.",
    why: "Se usa para firmar sesiones, tokens CSRF, y otros artefactos de seguridad.",
    impact: "Forgery de sesiones, CSRF bypass, token manipulation.",
    whoAffected: "Sesiones Django activas; atacante puede impersonar usuarios sin contraseña.",
  },
  SECRET_FLASK_SESSION_KEY: {
    what: "Flask SECRET_KEY está en código.",
    why: "Usado para firmar cookies de sesión.",
    impact: "Forgery de cookies de sesión, session riding.",
    whoAffected: "Usuarios de Flask app; atacante puede crear sesiones válidas sin autenticación.",
  },
  // A04 Extended
  CONFIG_CSP_UNSAFE: {
    what: "Content-Security-Policy incluye `unsafe-inline` o `unsafe-eval`.",
    why: "Debilita significativamente CSP (su propósito es bloquear inline scripts).",
    impact: "XSS inline no bloqueado; cualquier bug XSS derrota toda protección CSP.",
    whoAffected: "Usuarios logueados; XSS puede robar sesiones, modificar datos, malware.",
  },
  CONFIG_XFRAME_MISSING: {
    what: "Header X-Frame-Options no está configurado en la aplicación.",
    why: "Permite que página se cargue dentro de frames/iframes ajenos.",
    impact: "Clickjacking: usuario cree cliquear botón legítimo pero actúa en página oculta.",
    whoAffected: "Usuarios; acciones no consensuadas (transferencia dinero, cambio email, delete).",
  },
  CONFIG_HSTS_MISSING: {
    what: "Header Strict-Transport-Security (HSTS) no está configurado.",
    why: "Sin HSTS, navegador puede ser forzado a HTTP en primera conexión.",
    impact: "SSL stripping attack: MitM downgrade fuerza HTTP antes de certificado validation.",
    whoAffected: "Usuarios en redes públicas/Wi-Fi; cookies de sesión pueden ser interceptadas.",
  },
  CONFIG_HSTS_WEAK: {
    what: "HSTS max-age es muy bajo (< 1 año).",
    why: "Ventana corta entre rotaciones de certificado y conocimiento client-side.",
    impact: "Reducida protección contra SSL stripping si esperar expiración HSTS.",
    whoAffected: "Bajo; best practice es ≥1 año. Google preload list requiere 18 meses.",
  },
  CONFIG_COOKIE_INSECURE: {
    what: "Cookie tiene `httpOnly: false` o `secure: false`.",
    why: "httpOnly=false: XSS puede robar. secure=false: HTTP permite interceptación.",
    impact: "Session theft via XSS (httpOnly) o MitM (secure).",
    whoAffected: "Usuarios; especialmente admin cookies si roban privs.",
  },
  CONFIG_RATE_LIMIT_MISSING: {
    what: "Endpoints no tienen rate limiting configurado.",
    why: "Sin limits, atacante puede spam infinitamente: brute force, DDoS, resource exhaustion.",
    impact: "Account takeover (brute force password), negation of service.",
    whoAffected: "Disponibilidad del servicio; usuarios en credential stuffing campaigns.",
  },
  // A08 Extended
  PATTERN_JAVA_OBJECT_INPUT_STREAM: {
    what: "Java ObjectInputStream usado para deserializar datos externos.",
    why: "Deserialization gadget chains pueden ejecutar código arbitrario.",
    impact: "RCE durante `readObject()` si stream contiene gadget malicioso.",
    whoAffected: "Servidor Java completo; ejecución con permisos del proceso Java.",
  },
  PATTERN_DOTNET_BINARY_FORMATTER: {
    what: "BinaryFormatter o DataContractDeserializer usado en .NET.",
    why: "Microsoft deprecó BinaryFormatter por vulnerabilidades RCE no parchables.",
    impact: "RCE si deserializa datos no confiables.",
    whoAffected: ".NET proceso completo corriendo con permisos de app.",
  },
  PATTERN_PHP_UNSERIALIZE: {
    what: "PHP unserialize() recibe datos desde GET/POST/REQUEST.",
    why: "Deserialización PHP llama `__wakeup()` y `__destruct()` de objetos maliciosos.",
    impact: "RCE si hay gadget chain; POP (Property Oriented Programming) attacks.",
    whoAffected: "PHP process; posible file read/write, deletion, DB access.",
  },
  PATTERN_RUBY_MARSHAL_LOAD: {
    what: "Ruby Marshal.load() o YAML.load() procesa datos externo.",
    why: "Marshal.load ejecuta código Ruby durante deserialización.",
    impact: "RCE inmediato sin gadget chains requeridas (más directo que Java).",
    whoAffected: "Ruby process; posible code execution, file system access.",
  },
  // A03 Extended
  PATTERN_LDAP_INJECTION: {
    what: "Construcción dinámica de filtros LDAP con datos de usuario.",
    why: "Caracteres especiales LDAP no escapados permiten modificar lógica del filtro.",
    impact: "Auth bypass (siempre true), enumeración usuarios, información disclosure.",
    whoAffected: "Autenticación LDAP; posible bypass y acceso no autorizado a directory.",
  },
  PATTERN_XPATH_INJECTION: {
    what: "XPath queries construidas dinámicamente con entrada del usuario.",
    why: "XPath no parametrizado permite navegación arbitraria del árbol XML.",
    impact: "Información disclosure (lectura de nodos privados), lógica bypass.",
    whoAffected: "Datos XML; posible exfiltración de información sensible.",
  },
  PATTERN_COMMAND_INJECTION_SHELL: {
    what: "Ejecución shell con concatenación directa de datos del usuario.",
    why: "Shell interpreta caracteres especiales: backticks, pipes, redirects.",
    impact: "Ejecución arbitraria de comandos del sistema con permisos del proceso.",
    whoAffected: "Host completo; posible lectura archivos, exfiltración datos, lateral movement.",
  },
  PATTERN_TEMPLATE_INJECTION: {
    what: "Template rendering con código del usuario sin sandbox.",
    why: "Template engines ejecutan expresiones; usuario input podría inyectar código.",
    impact: "SSTI (Server-Side Template Injection) permite RCE.",
    whoAffected: "Servidor; acceso a variables server, file system, posible RCE.",
  },
  PATTERN_XXE_INJECTION: {
    what: "Parsing XML sin desactivar DTDs y ENTITY declarations.",
    why: "Entidades XML pueden referenciar archivos del sistema o URLs internas.",
    impact: "XXE attack: file read, SSRF a metadata endpoints, billion laughs DoS.",
    whoAffected: "Servidor; información disclosure (files), SSRF a infraestructura interna.",
  },
  PATTERN_NOSQL_INJECTION: {
    what: "NoSQL query (MongoDB $where) ejecuta código JavaScript con datos del usuario.",
    why: "$where evalúa JavaScript; equivalente a SQL injection en MongoDB.",
    impact: "Manipulación queries, auth bypass, información disclosure.",
    whoAffected: "Datos MongoDB; posible robo de documentos completos.",
  },
  // A03 Injection Engines
  INJECTION_LDAP: {
    what: "Se construye filtro LDAP dinámicamente con entrada de usuario.",
    why: "Caracteres especiales LDAP no escapados permiten cambiar lógica de búsqueda.",
    impact: "Auth bypass, enumeración de usuarios, acceso a directory privado.",
    whoAffected: "Usuarios y admins de directory LDAP; posible bypass autenticación.",
  },
  INJECTION_XPATH: {
    what: "Expresión XPath se construye concatenando datos del usuario.",
    why: "XPath no parametrizado permite navegar arbitrariamente el árbol XML.",
    impact: "Información disclosure de nodos privados, lógica bypass.",
    whoAffected: "Datos XML procesados; información sensitive podría leerse.",
  },
  INJECTION_COMMAND_SHELL: {
    what: "Comando shell ejecutado interpolando variables del usuario.",
    why: "Shell interpreta caracteres especiales: pipes, redirects, command chaining.",
    impact: "Ejecución arbitraria de comandos del sistema con permisos del proceso.",
    whoAffected: "Servidor/host completo; acceso a filesystem, exfiltración de datos.",
  },
  INJECTION_TEMPLATE_SSTI: {
    what: "Template renderizado con código del usuario sin sandbox.",
    why: "Template engines ejecutan expresiones; input podría inyectar código.",
    impact: "SSTI (Server-Side Template Injection) permite RCE accediendo variables server.",
    whoAffected: "Servidor; acceso variables globales, file system, posible RCE total.",
  },
  INJECTION_XXE: {
    what: "Parsing XML sin desactivar DTD y ENTITY declarations.",
    why: "Entidades XML pueden referenciar archivos internos o URLs.",
    impact: "XXE attack: lectura de archivos privados, SSRF, billion laughs DoS.",
    whoAffected: "Servidor; information disclosure (files), SSRF a infraestructura interna.",
  },
  INJECTION_NOSQL: {
    what: "NoSQL query (MongoDB $where, $function) ejecuta código JavaScript.",
    why: "$where evalúa JavaScript; equivalente a SQL injection.",
    impact: "Manipulación de queries, auth bypass, acceso a documentos.",
    whoAffected: "Base de datos; posible robo de documentos completos.",
  },
  INJECTION_GRAPHQL: {
    what: "Query/schema GraphQL construida dinámicamente sin limitación.",
    why: "Sin validación de profundidad/complejidad, atacante puede queries costosas.",
    impact: "GraphQL DoS, enumeración de schema, information disclosure.",
    whoAffected: "API GraphQL; disponibilidad y exposición de datos.",
  },
  INJECTION_SQL_DYNAMIC: {
    what: "SQL construida dinámicamente concatenando variables del usuario.",
    why: "Un apóstrofe permite escapar string y ejecutar SQL adicional.",
    impact: "SQL injection: lectura/modificación/borrado de BD, acceso escalado.",
    whoAffected: "Base de datos completa; datos clientes y operacionales.",
  },
  INJECTION_REGEX_DOS: {
    what: "Expresión regular con backtracking exponencial usado con entrada del usuario.",
    why: "Entrada larga con patrón mal diseñado causa ReDoS (regex DoS).",
    impact: "Denegación de servicio (DoS), CPU al 100%, timeouts.",
    whoAffected: "Disponibilidad de servicio; usuarios normales get timeouts.",
  },
  INJECTION_PATH_TRAVERSAL: {
    what: "Lectura de archivo usando ruta que incluye parámetro de usuario.",
    why: "Sin validación, ../ permite acceder archivos fuera del directorio esperado.",
    impact: "Lectura de archivos sensibles: .env, .git, config, /etc/passwd.",
    whoAffected: "Secretos en filesystem; información disclosure masiva.",
  },
  INJECTION_LOG_INJECTION: {
    what: "Entrada de usuario logueda sin sanitizar newlines/caracteres especiales.",
    why: "Newlines pueden inyectar entries falsas que afecten auditoría de logs.",
    impact: "Log tampering, covers tracks de ataque, confusión en análisis de incidente.",
    whoAffected: "Integrity de audit logs; posible cover-up de ataques.",
  },
  // A05 Integrity Engines
  INTEGRITY_AUTO_UPDATE: {
    what: "Código de auto-actualización sin verificar integridad (hash/firma).",
    why: "Sin verificación, build descarga e instala versión modificada sin saber.",
    impact: "Supply chain attack: update malicioso remplaza código legitimó.",
    whoAffected: "Todos usuarios del software; distribuye malware masivamente.",
  },
  INTEGRITY_POSTINSTALL_SCRIPT: {
    what: "Script post-install en package.json ejecuta comandos peligrosos.",
    why: "npm run install hooks ejecutan antes de que veamos código.",
    impact: "Ejecución de código malicioso durante `npm install` sin consentimiento.",
    whoAffected: "Máquina del desarrollador; acceso a credenciales, secretos, SSH.",
  },
  INTEGRITY_NO_LOCK_FILE: {
    what: "Proyecto sin lock file (package-lock.json, yarn.lock, Gemfile.lock).",
    why: "Sin lock, versiones de dependencias pueden cambiar entre instalaciones.",
    impact: "Supply chain attack: versión maliciosa de dependencia reemplaza legítima.",
    whoAffected: "Todo proyecto que depende de versiones inconsistentes.",
  },
  INTEGRITY_INSECURE_REGISTRY: {
    what: "Fuente de paquetes no verificada o insegura configurada.",
    why: "Registry no oficial o HTTP permite MITM e inyección de código.",
    impact: "Descarga de paquete malicioso en lugar del legítimo.",
    whoAffected: "Proyecto y developers usando registry comprometido.",
  },
  INTEGRITY_MISSING_CHECKSUM: {
    what: "Descarga de artifact/librería sin validar hash/checksum después.",
    why: "Sin verificación, MITM puede remplazar archivo con versión maliciosa.",
    impact: "Ejecución de código malicioso de origen no verificado.",
    whoAffected: "Build pipeline; posible compromiso total del binario producido.",
  },
  INTEGRITY_PYTHON_NO_LOCK: {
    what: "requirements.txt Python sin hash verificable de integridad.",
    why: "Sin hashes, pip puede instalar versión diferente o modificada.",
    impact: "Versión maliciosa de dependencia instalada sin detección.",
    whoAffected: "Entorno Python; acceso a credenciales y lógica de app.",
  },
  INTEGRITY_LOOSE_VERSION_CONSTRAINTS: {
    what: "Restricciones de versión muy abiertas (*, latest, rangos amplios).",
    why: "Permite cambios no controlados en dependencias.",
    impact: "Actualización automática a versión maliciosa o breaking change.",
    whoAffected: "Estabilidad y seguridad de proyecto a largo plazo.",
  },
  INTEGRITY_UNSIGNED_COMMITS: {
    what: "Commits en historio Git sin firma GPG verificable.",
    why: "Sin firma, commits pueden haber sido inyectados o modificados.",
    impact: "Posible inyección de código malicioso en historio sin detección.",
    whoAffected: "Integridad del código fuente; colaboradores podrían no notarlo.",
  },
  INTEGRITY_GIT_SUBMODULE_LOOSE: {
    what: "Git submodule sigue branch en lugar de commit específico.",
    why: "Branch puede ser forzado a apuntar código malicioso.",
    impact: "Inyección de código malicioso vía submodule update.",
    whoAffected: "Proyecto principal; código de submodule comprometido.",
  },
  INTEGRITY_DOCKER_NO_DIGEST: {
    what: "Docker image referenciada solo por tag, sin digest SHA256.",
    why: "Tag puede ser remplazado; digest SHA256 es inmutable.",
    impact: "Pull de imagen maliciosa si tag es forzado.",
    whoAffected: "Container runtime; todo código en container es comprometido.",
  },
  INTEGRITY_EXTERNAL_SCRIPT_NO_VERIFY: {
    what: "Script externo descargado e inmediatamente ejecutado.",
    why: "Sin verificación de hash/firma, MITM puede modificar script.",
    impact: "Ejecución de código malicioso desde internet.",
    whoAffected: "Máquina ejecutando script; acceso completo con permisos del usuario.",
  },
  INTEGRITY_ARTIFACT_HTTP: {
    what: "Artifact/librería descargada vía HTTP (sin TLS).",
    why: "HTTP permite MITM inyectar código malicioso.",
    impact: "Descarga de artifact malicioso remplazando legítimo.",
    whoAffected: "Build pipeline; todo binario/librería descargada puede estar compromisa.",
  },
  // A01 Access Control
  ACCESSCONTROL_ROUTE_NO_AUTH: {
    what: "Ruta sensible (API, admin, dashboard) sin autenticación visible.",
    why: "Sin middleware de auth, cualquiera puede acceder sin credenciales.",
    impact: "Acceso no autorizado a datos privados o funciones administrativas.",
    whoAffected: "Todos usuarios; información sensible pública o acciones no consentidas.",
  },
  ACCESSCONTROL_IDOR: {
    what: "Acceso a recurso por ID sin verificar que pertenece al usuario actual.",
    why: "Sin validación, atacante puede cambiar ID en URL/API y acceder recursos ajenos.",
    impact: "Lectura de información privada de otros usuarios (emails, documentos, datos).",
    whoAffected: "Privacidad de todos usuarios; información lateral disclosure.",
  },
  ACCESSCONTROL_NO_AUTHORIZATION: {
    what: "Operación sensible (delete, admin actions) sin verificación de permisos.",
    why: "Sin check de rol/permission, usuario regular podría ejecutar operaciones admin.",
    impact: "Escalada de privilegios; usuario normal se comporta como admin.",
    whoAffected: "Integridad de datos; acciones no autorizadas con permisos elevados.",
  },
  ACCESSCONTROL_PUBLIC_SENSITIVE: {
    what: "Endpoint con nombre sensitivo (secret, admin) sin protección visible.",
    why: "Nombre sugiere datos sensibles. Sin auth, accesible públicamente.",
    impact: "Exposición accidental de datos o funcionalidad sensible.",
    whoAffected: "Confidencialidad de datos especificados por nombre de ruta.",
  },
  ACCESSCONTROL_PRIV_ESCALATION: {
    what: "Rol de usuario asignado directamente desde parámetro del cliente.",
    why: "Si cliente controla `role` en request, atacante se asigna a sí mismo admin.",
    impact: "Escalada de privilegios: usuario regular se vuelve admin.",
    whoAffected: "Control administrativo compromisa completamente.",
  },
  ACCESSCONTROL_FUNCTION_BYPASS: {
    what: "Función con nombre administrativo (delete, admin) sin verificación de autorización.",
    why: "Nombre sugiere acción sensible. Sin guards, ejecutable por cualquiera.",
    impact: "Acciones no autorizadas con permisos de función.",
    whoAffected: "Integridad de datos; operaciones potencialmente destructivas.",
  },
  ACCESSCONTROL_HORIZONTAL_ESCALATION: {
    what: "Acceso a datos/cuenta de otro usuario del mismo nivel (ej: otro usuario regular).",
    why: "Sin validación de ownership, usuario A puede ver datos de usuario B.",
    impact: "Información disclosure masiva entre usuarios.",
    whoAffected: "Privacidad de todos usuarios del sistema.",
  },
  // A07 Auth Failures
  AUTHFAIL_WEAK_PASSWORD_POLICY: {
    what: "Política de contraseña muy permisiva (< 8 caracteres, sin requisitos complejidad).",
    why: "Contraseñas débiles se rompen fácilmente por diccionario/brute force.",
    impact: "Toma de cuenta; atacante rompe password rápidamente.",
    whoAffected: "Cuentas de usuarios; riesgo proporcional a debilidad de política.",
  },
  AUTHFAIL_NO_MFA: {
    what: "Autenticación solo por password, sin segundo factor (MFA/2FA).",
    why: "Sin 2FA, phishing, keylogger, o password breach compromete completamente cuenta.",
    impact: "Toma de cuenta fácil; sin segundo factor defensivo.",
    whoAffected: "Todas cuentas; especialmente admin/sensitivas.",
  },
  AUTHFAIL_SESSION_FIXATION: {
    what: "ID de sesión no se regenera después de login (mantiene ID pre-login).",
    why: "Atacante puede fijar session ID antes de login. Víctima inicia sesión, atacante obtiene acceso.",
    impact: "Toma de sesión sin credenciales reales.",
    whoAffected: "Usuarios; especialmente en wi-fi público sin protección.",
  },
  AUTHFAIL_HARDCODED_CREDENTIALS: {
    what: "Credenciales hardcodeadas para verificar autenticación.",
    why: "Credenciales en código fuente visibles a cualquiera con acceso a repo.",
    impact: "Acceso con credenciales fijas; bypass de autenticación.",
    whoAffected: "Cuentas hardcodeadas; riesgo compartido en todo equipo.",
  },
  AUTHFAIL_NO_PASSWORD_EXPIRATION: {
    what: "Contraseñas nunca expiran o sesiones sin timeout de inactividad.",
    why: "Credenciales old/stolen reutilizables indefinidamente.",
    impact: "Acceso prolongado aunque contraseña leaked hace meses.",
    whoAffected: "Seguridad a largo plazo; credenciales old siguen válidas.",
  },
  AUTHFAIL_JWT_NO_EXPIRATION: {
    what: "JWT emitido sin campo 'exp' (expiration).",
    why: "Token válido indefinidamente. Si leaked, acceso perpetuo.",
    impact: "Token stolen = acceso no limitado en tiempo.",
    whoAffected: "Cualquier JWT en circulación; riesgo long-lived.",
  },
  AUTHFAIL_WEAK_TOKEN_GENERATION: {
    what: "Token/sessionId generado con Math.random() o método no-criptográfico.",
    why: "Tokens predecibles pueden adivinarse sin ser leaked.",
    impact: "Toma de sesión sin necesidad de leak; guessable tokens.",
    whoAffected: "Todas sesiones; atacante puede generar tokens válidos.",
  },
  AUTHFAIL_NO_CSRF_PROTECTION: {
    what: "Endpoints de mutación (POST, PUT, DELETE) sin validación de CSRF token.",
    why: "Atacante puede hacer requests en nombre de usuario logueado si lo engaña.",
    impact: "Acciones no consentidas: transfer dinero, cambio datos, delete.",
    whoAffected: "Usuarios; acciones no consentidas posibles.",
  },
  AUTHFAIL_INSECURE_PASSWORD_RESET: {
    what: "Token de reset de contraseña generado predeciblemente o sin expiración.",
    why: "Atacante puede adivinar o usar token expirado para reset.",
    impact: "Reset no autorizado de contraseña; toma de cuenta.",
    whoAffected: "Cualquier cuenta; especialmente sin segundo factor.",
  },
  AUTHFAIL_ACCOUNT_ENUMERATION: {
    what: "Endpoint de login devuelve errores diferentes para usuario existente vs no-existente.",
    why: "Atacante puede enumerar usuarios válidos.",
    impact: "Información disclosure de usuarios existentes; facilita targeting.",
    whoAffected: "Base de usuarios; privacidad sobre existencia de cuentas.",
  },
  AUTHFAIL_NO_BRUTE_FORCE_PROTECTION: {
    what: "Endpoint de login sin rate limiting o protección contra intentos múltiples.",
    why: "Atacante puede hacer requests ilimitadas para romper password.",
    impact: "Brute force attack exitoso; toma de cuenta.",
    whoAffected: "Cuentas con passwords débiles; DoS possible.",
  },
  // A09 Logging & Monitoring
  LOGGING_MISSING_CRITICAL_EVENTS: {
    what: "Eventos críticos (login, logout, cambio password) no loguados.",
    why: "Sin logs, impossible detectar o auditar acceso no autorizado.",
    impact: "Imposible detectar breach o acceso malicioso retrospectively.",
    whoAffected: "Auditoria; forensics después de incident.",
  },
  LOGGING_MISSING_ERROR_HANDLER: {
    what: "Try-catch sin logging del error capturado.",
    why: "Errores silenciosos ocultos; debugging y forensics imposible.",
    impact: "Errores invisibles; operaciones fallidas no detectadas.",
    whoAffected: "Debugging; operaciones ocultas.",
  },
  LOGGING_CONSOLE_LOG_PRODUCTION: {
    what: "console.log/warn/error usado en código (no persiste en production).",
    why: "console.log se pierde si stderr no redirigido. No llega a logging system.",
    impact: "Logs importantes desaparecen en producción.",
    whoAffected: "Observabilidad; eventos desaparecen.",
  },
  LOGGING_NO_TIMESTAMP: {
    what: "Logs sin timestamp.",
    why: "Imposible correlacionar eventos temporalmente.",
    impact: "Análisis de forensics imposible; timeline desconocida.",
    whoAffected: "Incident response; análisis de causa raíz.",
  },
  LOGGING_SENSITIVE_DATA: {
    what: "Passwords, tokens, o secretos loguados.",
    why: "Credenciales en logs = logs son secreto igual que credencial.",
    impact: "Logs son ahora objetivo valioso; fuga de credenciales via logs.",
    whoAffected: "Confidencialidad de credenciales; logs = archivo de secretos.",
  },
  LOGGING_NOT_STRUCTURED: {
    what: "Logs con formato string en lugar de campos estructurados.",
    why: "Imposible parsear automáticamente o buscar eficientemente.",
    impact: "Análisis de logs manual y lento; alerting impossibly.",
    whoAffected: "Operaciones; SIEM, alerting, dashboards.",
  },
  LOGGING_NO_CORRELATION_ID: {
    what: "Logs sin trace/correlation ID (request tracing).",
    why: "Sin ID, imposible seguir request a través de sistema distribuido.",
    impact: "Tracing distribido imposible; debug de flow entre services.",
    whoAffected: "Microservices debugging; distributed tracing.",
  },
  LOGGING_INSECURE_STORAGE: {
    what: "Archivos .log almacenados públicamente o sin permisos restringidos.",
    why: "Cualquiera con acceso filesystem puede leer logs = lee secretos loguados.",
    impact: "Logs públicos = acceso a información sensible.",
    whoAffected: "Confidencialidad de logs; información disclosure.",
  },
  LOGGING_NO_ALERTS: {
    what: "Eventos críticos loguados pero sin alertas configuradas.",
    why: "Sin alertas, breach detectado horas/días después.",
    impact: "Detección retrasada de incidents; ventana de daño extendida.",
    whoAffected: "Tiempo de detección; response time.",
  },
  LOGGING_LOG_INJECTION: {
    what: "Entrada de usuario loguada sin sanitizar newlines.",
    why: "Newlines inyectadas pueden falsificar logs posteriores.",
    impact: "Log tampering; cobertura de tracks de ataque.",
    whoAffected: "Integridad de audit trail.",
  },
  // A10 SSRF
  SSRF_UNVALIDATED_URL: {
    what: "URL controlada por usuario usada en fetch/request sin validación.",
    why: "Atacante controla destino de petición HTTP.",
    impact: "SSRF: acceso a servicios internos, metadata endpoints, exfiltración.",
    whoAffected: "Servicios internos; metadata endpoints; cualquier host alcanzable.",
  },
  SSRF_NO_PROTOCOL_VALIDATION: {
    what: "Sin validación de protocolo URL (podría ser file://, gopher://).",
    why: "Otros protocolos pueden acceder filesystems o servicios.",
    impact: "Lectura de archivos locales; acceso a servicios legados.",
    whoAffected: "Filesystem; servicios internos.",
  },
  SSRF_LOCALHOST_ACCESS: {
    what: "URL referenciando localhost o rangos IP privados.",
    why: "Acceso a servicios internos no expuestos a público.",
    impact: "Acceso a database, cache, admin panels internos.",
    whoAffected: "Servicios internos; infraestructura privada.",
  },
  SSRF_AWS_METADATA: {
    what: "Petición a AWS metadata endpoint (169.254.169.254).",
    why: "Metadata endpoint expone credenciales IAM temporales.",
    impact: "Acceso a credenciales AWS; control de infraestructura.",
    whoAffected: "Credenciales IAM; acceso a recursos AWS.",
  },
  SSRF_DNS_REBINDING: {
    what: "Resolución DNS sin re-validación que IP es pública.",
    why: "DNS rebinding: resolver returns private IP después validación.",
    impact: "Bypass de validación IP; acceso a internals.",
    whoAffected: "Servicios internos; validación puede bypassearse.",
  },
  SSRF_OPEN_REDIRECT_SSRF: {
    what: "Combo de open redirect + SSRF (backend sigue redirect a internal IP).",
    why: "Open redirect + backend siguiendo redirects = acceso interno.",
    impact: "Acceso a servicios internos vía open redirect chain.",
    whoAffected: "Servicios internos; infraestructura.",
  },
  SSRF_WEBHOOK_NO_VALIDATION: {
    what: "Webhook/callback URL del usuario usado para petición sin validación.",
    why: "Atacante controla URL de webhook; puede ser IP privada.",
    impact: "SSRF vía webhook URL; acceso a internals.",
    whoAffected: "Servicios internos.",
  },
  SSRF_URL_PARSING_BYPASS: {
    what: "Validación URL podría bypassearse por parsing inconsistente.",
    why: "Diferentes parsers interpretan URLs diferente (encoding, unicode, etc).",
    impact: "Bypass de validación; SSRF efectivo.",
    whoAffected: "Validación URL; puede ser evitada.",
  },
  SSRF_PORT_SCANNING: {
    what: "Patrón de scanning iterativo de puertos vía SSRF.",
    why: "Atacante puede usar SSRF para enumerar puertos abiertos.",
    impact: "Port scanning de infraestructura interna.",
    whoAffected: "Enumeración de servicios internos.",
  },
  SSRF_TIMING_ATTACK_POSSIBLE: {
    what: "Timeout muy bajo en conexiones SSRF.",
    why: "Diferencias en timing pueden revelar si host/puerto existe.",
    impact: "Timing-based port scanning.",
    whoAffected: "Privacidad de topología interna.",
  },
  SSRF_NO_TLS_VERIFICATION: {
    what: "Petición HTTPS sin verificación de certificado SSL.",
    why: "Sin verificación, MITM puede interceptar.",
    impact: "MITM; interception de comunicación.",
    whoAffected: "Confidencialidad de comunicación.",
  },
};

export function educationFor(ruleId: string): Educational {
  return EDU_TEMPLATES[ruleId] ?? GENERIC;
}
